import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import CartProvider from "@/providers/cart-provider";

const kumbhSans = Kumbh_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sneakers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>
        <CartProvider>
          <div className="mx-auto max-w-[69.375rem]">
            <Navigation />
            {children}
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
